version: '3.4'

services:
  db: 
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123

  lukakry.calc.api:
    image: ${DOCKER_REGISTRY-}lukakrycalcapi
    build:
      context: .
      dockerfile: lukaKry.Cal.API/Dockerfile
    depends_on: 
      - db