version: "3.4"
services: 
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.Multi.nginx
    ports: 
            - 80:80
    restart: always
  client:
    build:
      context: ./angular-ivy
      dockerfile: Dockerfile.Multi.angular
    ports: 
      - 5000:80
  dncapi:
    build: 
      context: ./lukaKry.Cal.Api
      dockerfile: Dockerfile.Multi.api
    ports: 
      - 3000:80