FROM mcr.microsoft.com/dotnet/sdk:5.0 AS AS build
WORKDIR /app

COPY *.csproj .
COPY *.config .
RUN dotnet restore --disable-parallel --configfile ./nuget.config 
COPY . .
RUN dotnet publish -c Release -o build

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app

COPY --from=build /app/build .
ENTRYPOINT [ "dotnet", "AngularDncApp.dll" ]